resources:
  # - ../../base
  - base
  - namespace.yaml

namespace: dev

# namePrefix: dev-
# commonLabels:
#   environment: dev

patches:
  - target:
      kind: Deployment
      name: nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
