resources:
  - ../../../base
  - namespace.yaml

namespace: prod

# namePrefix: prod-
# commonLabels:
#   environment: prod

patches:
  - target:
      kind: Deployment
      name: nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
